apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
 # namespace: default 
spec:
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: my-vol
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
